### ISSUE TITLE
Provide compatibility with `CacheInterface`

### ISSUE THREAD

**Issue by shgysk8zer0** [shgysk8zer0/http#6]
Check that `Request`s & `Response`s are the same before and after `serialize()` & `unserialize()`.

In other words:

```php
<?php
$req = new Request();
$resp = new Response();
/**
 * Build up $req & $resp
 */

unserialize(serialize($req)); // Same as original Request?
unserialize(serialize($resp)); // Same as original Response?
```

One issue that I suspect difficulty in encountering is whether or not `CURLFile` can be serialized. I could easily create a custom class that just serializes the filename, type, & postname, but cannot guarantee that the file will still exist when unserialized.

## Tasks:
- [x] Ensure compatibility with `serialize()` & `unserialize()` for caching
- [ ] Determine cache keys from request URL & probably `Accept` & `Vary` headers
- [x] Implement a serializable file class extending `CURLFile`
- [ ] Determine method of setting expiration for cache (response headers, maybe?)
- [ ] Handle caching by an init preference, similar to JS's [`Request.cache`](https://developer.mozilla.org/en-US/docs/Web/API/Request/cache) preference
- [ ] Update example in README.md

**Comment by shgysk8zer0** [comment]
Perhaps I could provide cache key using `Request::__toString()`, allowing:

```php
if ($cache->has($req)) {
    $resp = $cache->get($req);
}
```

`Request` could then provide methods taking expiration & fallback args and work somewhat more directly with `CacheInterface`.

**Comment by shgysk8zer0** [comment]
Due to the complexity of HTTP caching, I do not think that the basic `CacheInterface` can be compatible. I need to be able to check ETags, make conditional requests, utilize Cache-Control headers, etc.
